import type { Food } from "./types";

export const seedFoods: Food[] = [
  {
    id: "seed-chicken-breast",
    name: "Chicken breast, cooked",
    servingGrams: 150,
    servingLabel: "1 fillet",
    pieceGrams: 150,
    nutrientsPer100: { calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, micronutrients: { sodiumMg: 74, cholesterolMg: 85, saturatedFatG: 1, potassiumMg: 256, calciumMg: 15, ironMg: 1, magnesiumMg: 29, zincMg: 1, vitaminAMcg: 3, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0.3, vitaminKMcg: 2, vitaminB12Mcg: 0.3, folateMcg: 4 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-egg",
    name: "Egg, large",
    servingGrams: 50,
    servingLabel: "1 egg",
    pieceGrams: 50,
    nutrientsPer100: { calories: 143, protein: 12.6, carbs: 0.7, fat: 9.5, fiber: 0, sugar: 0.4, micronutrients: { sodiumMg: 142, cholesterolMg: 372, saturatedFatG: 2.6, potassiumMg: 138, calciumMg: 56, ironMg: 1.8, magnesiumMg: 12, zincMg: 1.3, vitaminAMcg: 160, vitaminCMg: 0, vitaminDMcg: 2, vitaminEMg: 1.1, vitaminKMcg: 0.3, vitaminB12Mcg: 1.1, folateMcg: 47 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-rice",
    name: "White rice, cooked",
    servingGrams: 150,
    servingLabel: "1 bowl",
    nutrientsPer100: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, fiber: 0.4, sugar: 0.1, micronutrients: { sodiumMg: 1, cholesterolMg: 0, saturatedFatG: 0.1, potassiumMg: 35, calciumMg: 10, ironMg: 0.2, magnesiumMg: 12, zincMg: 0.5, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0.1, vitaminKMcg: 0.1, vitaminB12Mcg: 0, folateMcg: 3 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-banana",
    name: "Banana",
    servingGrams: 118,
    servingLabel: "1 medium banana",
    pieceGrams: 118,
    nutrientsPer100: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6, sugar: 12.2, micronutrients: { sodiumMg: 1, cholesterolMg: 0, saturatedFatG: 0.1, potassiumMg: 358, calciumMg: 5, ironMg: 0.3, magnesiumMg: 27, zincMg: 0.2, vitaminAMcg: 3, vitaminCMg: 8.7, vitaminDMcg: 0, vitaminEMg: 0.1, vitaminKMcg: 0.5, vitaminB12Mcg: 0, folateMcg: 20 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-oats",
    name: "Rolled oats, dry",
    servingGrams: 50,
    servingLabel: "½ cup",
    nutrientsPer100: { calories: 379, protein: 13.2, carbs: 67.7, fat: 6.5, fiber: 10.1, sugar: 1, micronutrients: { sodiumMg: 2, cholesterolMg: 0, saturatedFatG: 1.2, potassiumMg: 362, calciumMg: 52, ironMg: 4.3, magnesiumMg: 138, zincMg: 3.6, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0.4, vitaminKMcg: 0, vitaminB12Mcg: 0, folateMcg: 32 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-greek-yogurt",
    name: "Greek yogurt, 2%",
    servingGrams: 200,
    servingLabel: "1 bowl",
    nutrientsPer100: { calories: 73, protein: 9.9, carbs: 3.9, fat: 1.9, fiber: 0, sugar: 3.6, micronutrients: { sodiumMg: 47, cholesterolMg: 10, saturatedFatG: 1.2, potassiumMg: 141, calciumMg: 115, ironMg: 0.1, magnesiumMg: 11, zincMg: 0.6, vitaminAMcg: 28, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0.1, vitaminKMcg: 0.1, vitaminB12Mcg: 0.4, folateMcg: 7 } },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-beef-meatball",
    name: "Beef meatball, grilled",
    servingGrams: 95,
    servingLabel: "1 meatball",
    pieceGrams: 95,
    nutrientsPer100: { calories: 250, protein: 18, carbs: 5, fat: 18, fiber: 0.4, sugar: 0.5, micronutrients: { sodiumMg: 500, cholesterolMg: 80, saturatedFatG: 7, potassiumMg: 250, calciumMg: 20, ironMg: 2, magnesiumMg: 20, zincMg: 5, vitaminAMcg: 20, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0.2, vitaminKMcg: 2, vitaminB12Mcg: 2, folateMcg: 7 } },
    source: "seed",
  },
  {
    id: "seed-psyllium",
    name: "Psyllium husk",
    servingGrams: 10,
    servingLabel: "1 tbsp",
    nutrientsPer100: { calories: 200, protein: 2.5, carbs: 8, fat: 0.6, fiber: 78, sugar: 0, micronutrients: { sodiumMg: 9, cholesterolMg: 0, saturatedFatG: 0.1, potassiumMg: 170, calciumMg: 29, ironMg: 0.9, magnesiumMg: 50, zincMg: 1.1, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminEMg: 0, vitaminKMcg: 0, vitaminB12Mcg: 0, folateMcg: 5 } },
    source: "seed",
  },
];
