import type { Food } from "./types";

export const seedFoods: Food[] = [
  {
    id: "seed-chicken-breast",
    name: "Chicken breast, cooked",
    servingGrams: 150,
    servingLabel: "1 fillet",
    pieceGrams: 150,
    nutrientsPer100: { calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-egg",
    name: "Egg, large",
    servingGrams: 50,
    servingLabel: "1 egg",
    pieceGrams: 50,
    nutrientsPer100: { calories: 143, protein: 12.6, carbs: 0.7, fat: 9.5, fiber: 0, sugar: 0.4 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-rice",
    name: "White rice, cooked",
    servingGrams: 150,
    servingLabel: "1 bowl",
    nutrientsPer100: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, fiber: 0.4, sugar: 0.1 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-banana",
    name: "Banana",
    servingGrams: 118,
    servingLabel: "1 medium banana",
    pieceGrams: 118,
    nutrientsPer100: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6, sugar: 12.2 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-oats",
    name: "Rolled oats, dry",
    servingGrams: 50,
    servingLabel: "½ cup",
    nutrientsPer100: { calories: 379, protein: 13.2, carbs: 67.7, fat: 6.5, fiber: 10.1, sugar: 1 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-greek-yogurt",
    name: "Greek yogurt, 2%",
    servingGrams: 200,
    servingLabel: "1 bowl",
    nutrientsPer100: { calories: 73, protein: 9.9, carbs: 3.9, fat: 1.9, fiber: 0, sugar: 3.6 },
    source: "seed",
    verified: true,
  },
  {
    id: "seed-beef-meatball",
    name: "Beef meatball, grilled",
    servingGrams: 95,
    servingLabel: "1 meatball",
    pieceGrams: 95,
    nutrientsPer100: { calories: 250, protein: 18, carbs: 5, fat: 18, fiber: 0.4, sugar: 0.5 },
    source: "seed",
  },
  {
    id: "seed-psyllium",
    name: "Psyllium husk",
    servingGrams: 10,
    servingLabel: "1 tbsp",
    nutrientsPer100: { calories: 200, protein: 2.5, carbs: 8, fat: 0.6, fiber: 78, sugar: 0 },
    source: "seed",
  },
];
