"use client";
/* eslint-disable @next/next/no-img-element -- meal photos are dynamic user content. */

import { Info } from "lucide-react";
import { formatUnit, round } from "@/lib/nutrition";
import type { Meal, Micronutrients, Nutrition, Recipe } from "@/lib/types";

const micronutrientLabels: Array<{ key: keyof Micronutrients; label: string; unit: string }> = [{ key: "sodiumMg", label: "Sodium", unit: "mg" }, { key: "potassiumMg", label: "Potassium", unit: "mg" }, { key: "calciumMg", label: "Calcium", unit: "mg" }, { key: "ironMg", label: "Iron", unit: "mg" }, { key: "magnesiumMg", label: "Magnesium", unit: "mg" }, { key: "zincMg", label: "Zinc", unit: "mg" }, { key: "cholesterolMg", label: "Cholesterol", unit: "mg" }, { key: "saturatedFatG", label: "Saturated fat", unit: "g" }, { key: "vitaminAMcg", label: "Vitamin A", unit: "mcg" }, { key: "vitaminCMg", label: "Vitamin C", unit: "mg" }, { key: "vitaminDMcg", label: "Vitamin D", unit: "mcg" }, { key: "vitaminEMg", label: "Vitamin E", unit: "mg" }, { key: "vitaminKMcg", label: "Vitamin K", unit: "mcg" }, { key: "vitaminB12Mcg", label: "Vitamin B12", unit: "mcg" }, { key: "folateMcg", label: "Folate", unit: "mcg" }];

export function MealImageViewer({ meal }: { meal: Meal }) { return <div className="meal-image-viewer"><span className="eyebrow">Meal photo</span><h2>{meal.name}</h2><img src={meal.imageUrl} alt={`Photo of ${meal.name}`} /></div>; }

export function NutritionDetails({ meal, hideCalories, recipe, onClose }: { meal: Meal; hideCalories: boolean; recipe?: Recipe; onClose?: () => void }) { const nutrition = meal.nutrition; const micros = nutrition.micronutrients; return <div className="nutrition-details"><div className="sheet-header"><div><span className="eyebrow">{recipe ? "Saved recipe" : "Nutrition details"}</span><h2>{meal.name}</h2></div><span /></div>{recipe?.imageUrls?.length ? <div className="recipe-detail-photos">{recipe.imageUrls.map((url, index) => <img key={url} src={url} alt={`${recipe.name}, photo ${index + 1}`} />)}</div> : null}<div className="nutrition-detail-meta"><span>{meal.amount} {formatUnit(meal.unit, meal.amount)} · {meal.grams} g</span>{meal.estimated && <span className="estimate-pill">Estimated</span>}</div><section className="detail-section" aria-labelledby="macro-detail-heading"><div className="detail-section-heading"><h3 id="macro-detail-heading">Macros</h3><span>for this portion</span></div><div className="detail-grid macro-detail-grid">{!hideCalories && <div><span>Calories</span><strong>{Math.round(nutrition.calories)} <small>kcal</small></strong></div>}<div><span>Protein</span><strong>{round(nutrition.protein)} <small>g</small></strong></div><div><span>Carbs</span><strong>{round(nutrition.carbs)} <small>g</small></strong></div><div><span>Fat</span><strong>{round(nutrition.fat)} <small>g</small></strong></div><div><span>Fibre</span><strong>{round(nutrition.fiber)} <small>g</small></strong></div><div><span>Sugar</span><strong>{round(nutrition.sugar)} <small>g</small></strong></div></div></section>{recipe && <section className="detail-section recipe-detail-ingredients" aria-labelledby="recipe-foods-heading"><div className="detail-section-heading"><h3 id="recipe-foods-heading">Foods in this recipe</h3><span>{recipe.ingredients.length} items</span></div><ul>{recipe.ingredients.map((ingredient) => <li key={ingredient.id}><span>{ingredient.name}</span><small>{Math.round(ingredient.nutrition?.calories || 0)} kcal</small></li>)}</ul></section>}{micros && <section className="detail-section" aria-labelledby="micro-detail-heading"><div className="detail-section-heading"><h3 id="micro-detail-heading">Micronutrients</h3><span>label or catalogue data</span></div><div className="detail-grid micro-detail-grid">{micronutrientLabels.map(({ key, label, unit }) => <div key={key}><span>{label}</span><strong>{round(micros[key], 2)} <small>{unit}</small></strong></div>)}</div></section>}<div className="detail-footnote"><Info size={15} /> Values are estimates unless verified on the food label.</div>{onClose && <div className="sheet-actions"><button type="button" className="secondary-button" onClick={onClose}>Close</button></div>}</div>; }

export function DailyNutritionBreakdown({ nutrition, hideCalories }: { nutrition: Nutrition; hideCalories: boolean }) { const micros = nutrition.micronutrients; return <div className="macro-breakdown" id="daily-nutrition-breakdown"><section className="detail-section macro-detail-section" aria-labelledby="daily-macro-heading"><div className="detail-section-heading"><h3 id="daily-macro-heading">Macronutrients</h3><span>today’s total</span></div><div className="detail-grid macro-detail-grid">{!hideCalories && <div className="nutrition-detail-card calories"><span>Calories</span><strong>{Math.round(nutrition.calories)} <small>kcal</small></strong></div>}<div className="nutrition-detail-card protein"><span>Protein</span><strong>{round(nutrition.protein)} <small>g</small></strong></div><div className="nutrition-detail-card carbs"><span>Carbs</span><strong>{round(nutrition.carbs)} <small>g</small></strong></div><div className="nutrition-detail-card fat"><span>Fat</span><strong>{round(nutrition.fat)} <small>g</small></strong></div><div className="nutrition-detail-card fiber"><span>Fibre</span><strong>{round(nutrition.fiber)} <small>g</small></strong></div><div className="nutrition-detail-card sugar"><span>Sugar</span><strong>{round(nutrition.sugar)} <small>g</small></strong></div></div></section>{micros && <section className="detail-section micro-detail-section" aria-labelledby="daily-micro-heading"><div className="detail-section-heading"><h3 id="daily-micro-heading">Micronutrients</h3><span>today’s total</span></div><div className="detail-grid micro-detail-grid">{micronutrientLabels.map(({ key, label, unit }) => <div key={key} className={`nutrition-detail-card micro${micros[key] === 0 ? " is-zero" : ""}`}><span>{label}</span><strong>{round(micros[key], 2)} <small>{unit}</small></strong></div>)}</div></section>}</div>; }
